dist:
  dtype: bfloat16
model:
  backbone:
    hf_config:
      num_channels: 1
      patch_size: 4
      num_stages: 4
      hidden_sizes:
      - 352
      - 704
      - 1408
      - 2816
      depths:
      - 3
      - 3
      - 27
      - 3
      hidden_act: gelu
      initializer_range: 0.02
      layer_norm_eps: 1.0e-12
      drop_path_rate: 0.0
      image_size: 1920
      out_features:
      - stage1
      - stage2
      - stage3
      - stage4
      out_indices: null
    from_scratch: false
  bifpn:
    block:
      base_level: 4
      bn:
        eps: 1.0e-05
        momentum: 0.1
      down_scale_factor: 0.5
      fusion:
        eps: 1.0e-05
      num_features: 512
      num_levels: 4
      relu_inplace: false
      up_scale_factor: 2
    num_blocks: 4
  freezes_backbone: false
  seg_head:
    base_scale_factor: 2
    num_classes: 2
    num_groups: 32
    out_channels: 256
    up_scale_factor:
    - 4
    - 8
    - 16
    - 32
    uses_learned_upsample: true
  uses_random_weights: false
